add_comment_feature&modify_about_me
pikerple/2020_Google_SPS pull request #3
Opened 2020-07-20 06:04 UTC by pikerple

2020-07-20 11:24 UTC, layog requested changes
Hi Mandy,

In your previous PR, you are calling `/new-task` when adding a new comment. I think you should setup another endpoint for comments and not use the same task list. Sorry I missed this point in the previous PR, my bad!

2020-08-25 07:26 UTC, pikerple commented
I've modify it and add week3 libraries feature.

2020-08-25 12:25 UTC, layog approved these changes
Hi Mandy,

There are some formatting errors, but I am not going to block the merging as this is the last week and you might not have time to work on this again.

2020-08-25 12:25 UTC, layog commented on portfolio/src/main/java/com/google/sps/servlets/Comment.java
> +	String imageUrl;
nit: Formatting error

2020-08-25 12:25 UTC, layog commented on portfolio/src/main/java/com/google/sps/servlets/DataServlet.java
> +		// Put the comments into a list in order to use gson to convert
nit: Formatting

2020-08-26 04:00 UTC, merged